packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.35.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  zod: ^4.1.5

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
